//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_list.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public string Natural_ID_number { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Father_name { get; set; }
        public int Class_number { get; set; }
    }
}
